apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-pod
  template:
    metadata:
      labels:
        app: go-app-pod
    spec:
      containers:
        - name: go-app
          image: go-app:dev  # LOCAL image name
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app-pod
  ports:
    - port: 7000
      targetPort: 7000