version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocritic
    - gocyclo
    - misspell
    - revive
    - staticcheck
    - unused
    - wrapcheck
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 40
      statements: 20
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - opinionated
    gocyclo:
      min-complexity: 10
    revive:
      rules:
        - name: var-naming
        - name: package-comments
        - name: exported
        - name: indent-error-flow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
