kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090  # Prometheus NodePort
        hostPort: 30090
        protocol: TCP
      - containerPort: 30030  # Grafana NodePort
        hostPort: 30030
        protocol: TCP
      - containerPort: 30080  # NGINX NodePort
        hostPort: 30080
        protocol: TCP
      - containerPort: 8000  # Python App NodePort
        hostPort: 8000
        protocol: TCP
      - containerPort: 12000  # MkDocs NodePort
        hostPort: 12000
        protocol: TCP
  - role: worker
  - role: worker
