# This file maps ports between the host and the kind cluster.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090  # Prometheus NodePort
        hostPort: 30090
        protocol: TCP
      - containerPort: 30030  # Grafana NodePort
        hostPort: 30030
        protocol: TCP
      - containerPort: 30080  # NGINX NodePort
        hostPort: 30080
        protocol: TCP
      - containerPort: 32000  # Python App NodePort
        hostPort: 8000
        protocol: TCP
      - containerPort: 31080  # Go App NodePort
        hostPort: 31080
        protocol: TCP
      - containerPort: 30800  # MkDocs NodePort
        hostPort: 12000
        protocol: TCP
  - role: worker
  - role: worker