site_name: MkDocs Kubernetes Project
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - def_list