apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment
  labels:
    app: mkdocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      containers:
      - name: mkdocs
        image: mkdocs-documentation:dev
        ports:
        - containerPort: 11000
---
apiVersion: v1
kind: Service
metadata:
  name: mkdocs-service
  labels:
    app: mkdocs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 11000
      nodePort: 30800
      protocol: TCP
  selector:
    app: mkdocs