apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'self'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'nginx-metrics'
        static_configs:
          - targets: ['nginx-exporter:9113']
      
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      
      - job_name: 'python-app'
        static_configs:
          - targets: ['python-app-service:8000']
        metrics_path: '/metrics'
        scrape_interval: 5s

