site_name: DevOps Project Documentation
site_url: https://jeremiaszmacura.github.io/devops-stack/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Adding a Service: adding-a-service.md
  - Design: design.md
  - Platform Decisions: platform-decisions.md
  - Monitoring: monitoring.md
  - End-to-End Tests: e2e-tests.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format